//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabasesCarPartsShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Parts = new HashSet<Part>();
        }
    
        public int CarID { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string ProductionYear { get; set; }
    
        public virtual ICollection<Part> Parts { get; set; }
    }
}
