//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabasesCarPartsShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int PartID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<float> BuyPrice { get; set; }
        public Nullable<float> SellPrice { get; set; }
        public Nullable<int> ShopID { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
